import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
/**
 * CollectionGrid Component
 *
 * Center panel displaying collected videos with real-time status
 */
export const CollectionGrid = ({ videos, selectedVideoId, onSelectVideo, getStatusColor, getStatusText, }) => {
    return (_jsxs("div", { children: [_jsxs("h2", { className: "text-lg font-bold text-gray-900 mb-4", children: ["Collected Videos (", videos.length, ")"] }), _jsx("div", { className: "grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4", children: videos.map((video) => (_jsxs("div", { onClick: () => onSelectVideo(video), className: `bg-white rounded-lg overflow-hidden shadow-md cursor-pointer transition-all hover:shadow-lg ${selectedVideoId === video.id ? 'ring-2 ring-blue-500' : ''}`, children: [_jsxs("div", { className: "relative w-full h-32 bg-gray-200 flex items-center justify-center overflow-hidden", children: [video.thumbnailUrl ? (_jsx("img", { src: video.thumbnailUrl, alt: video.title || 'Video', className: "w-full h-full object-cover" })) : (_jsxs("div", { className: "flex flex-col items-center justify-center text-gray-400", children: [_jsx("svg", { className: "w-8 h-8 mb-2", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" }) }), _jsx("span", { className: "text-xs", children: video.platform })] })), _jsx("div", { className: `absolute top-2 right-2 px-2 py-1 rounded text-xs font-semibold ${getStatusColor(video.status)}`, children: getStatusText(video.status) }), _jsx("div", { className: "absolute top-2 left-2 px-2 py-1 rounded text-xs font-semibold bg-gray-800 text-white", children: video.platform === 'instagram' ? 'IG' : 'TT' })] }), _jsxs("div", { className: "p-3", children: [_jsx("h3", { className: "font-semibold text-gray-900 text-sm truncate", children: video.title || 'Untitled' }), video.durationSeconds && (_jsxs("p", { className: "text-xs text-gray-500 mt-1", children: [Math.floor(video.durationSeconds), "s"] })), video.tags.length > 0 && (_jsxs("div", { className: "flex flex-wrap gap-1 mt-2", children: [video.tags.slice(0, 2).map((tag) => (_jsx("span", { className: "inline-block bg-blue-100 text-blue-700 text-xs px-2 py-1 rounded", children: tag }, tag))), video.tags.length > 2 && (_jsxs("span", { className: "inline-block bg-gray-100 text-gray-700 text-xs px-2 py-1 rounded", children: ["+", video.tags.length - 2] }))] })), video.status === 'FAILED' && video.errorMessage && (_jsxs("p", { className: "text-xs text-red-600 mt-2 truncate", children: ["Error: ", video.errorMessage] }))] })] }, video.id))) })] }));
};
export default CollectionGrid;
