import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
export const TemplateCard = ({ template }) => {
    const navigate = useNavigate();
    const handleClick = () => {
        navigate(`/editor/${template.id}`);
    };
    return (_jsxs("div", { onClick: handleClick, className: "bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg hover:scale-105 transition-all duration-200 cursor-pointer", children: [_jsxs("div", { className: "relative w-full aspect-video bg-gray-200 overflow-hidden", children: [template.thumbnailUrl ? (_jsx("img", { src: template.thumbnailUrl, alt: template.name, className: "w-full h-full object-cover" })) : (_jsx("div", { className: "w-full h-full flex items-center justify-center bg-gradient-to-br from-gray-300 to-gray-400", children: _jsx("svg", { className: "w-12 h-12 text-gray-500", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 1.5, d: "M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" }) }) })), _jsxs("div", { className: "absolute bottom-2 right-2 bg-black bg-opacity-70 text-white px-2 py-1 rounded text-sm font-semibold", children: [template.durationSeconds, "s"] })] }), _jsxs("div", { className: "p-4", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2 line-clamp-2", children: template.name }), _jsx("div", { className: "flex items-center gap-2 mb-3", children: _jsx("span", { className: "inline-block bg-blue-100 text-blue-800 text-xs font-semibold px-2 py-1 rounded-full", children: template.category }) }), template.description && (_jsx("p", { className: "text-sm text-gray-600 line-clamp-2 mb-3", children: template.description })), template.tags && template.tags.length > 0 && (_jsxs("div", { className: "flex flex-wrap gap-1 mb-3", children: [template.tags.slice(0, 2).map((tag) => (_jsxs("span", { className: "inline-block bg-gray-100 text-gray-700 text-xs px-2 py-1 rounded", children: ["#", tag] }, tag))), template.tags.length > 2 && (_jsxs("span", { className: "inline-block text-gray-500 text-xs px-2 py-1", children: ["+", template.tags.length - 2] }))] })), _jsx("button", { onClick: (e) => {
                            e.stopPropagation();
                            handleClick();
                        }, className: "w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-lg transition-colors duration-200", children: "Use Template" })] })] }));
};
